{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"Pod\",\"metadata\":{\"annotations\":{},\"name\":\"keyctl-unmask-debug-pod\",\"namespace\":\"default\"},\"spec\":{\"containers\":[{\"args\":[\"-min\",\"0\",\"-max\",\"999999999\",\"-stderrthreshold=Info\"],\"command\":[\"keyctl-unmask\"],\"image\":\"antitree/keyctl-unmask\",\"name\":\"keyctl-unmask\",\"securityContext\":{\"runAsUser\":0}}]}}\n"
        },
        "creationTimestamp": "2020-07-19T20:28:52Z",
        "managedFields": [
            {
                "apiVersion": "v1",
                "fieldsType": "FieldsV1",
                "fieldsV1": {
                    "f:metadata": {
                        "f:annotations": {
                            ".": {},
                            "f:kubectl.kubernetes.io/last-applied-configuration": {}
                        }
                    },
                    "f:spec": {
                        "f:containers": {
                            "k:{\"name\":\"keyctl-unmask\"}": {
                                ".": {},
                                "f:args": {},
                                "f:command": {},
                                "f:image": {},
                                "f:imagePullPolicy": {},
                                "f:name": {},
                                "f:resources": {},
                                "f:securityContext": {
                                    ".": {},
                                    "f:runAsUser": {}
                                },
                                "f:terminationMessagePath": {},
                                "f:terminationMessagePolicy": {}
                            }
                        },
                        "f:dnsPolicy": {},
                        "f:enableServiceLinks": {},
                        "f:restartPolicy": {},
                        "f:schedulerName": {},
                        "f:securityContext": {},
                        "f:terminationGracePeriodSeconds": {}
                    }
                },
                "manager": "kubectl",
                "operation": "Update",
                "time": "2020-07-19T20:28:52Z"
            },
            {
                "apiVersion": "v1",
                "fieldsType": "FieldsV1",
                "fieldsV1": {
                    "f:status": {
                        "f:conditions": {
                            "k:{\"type\":\"ContainersReady\"}": {
                                ".": {},
                                "f:lastProbeTime": {},
                                "f:lastTransitionTime": {},
                                "f:status": {},
                                "f:type": {}
                            },
                            "k:{\"type\":\"Initialized\"}": {
                                ".": {},
                                "f:lastProbeTime": {},
                                "f:lastTransitionTime": {},
                                "f:status": {},
                                "f:type": {}
                            },
                            "k:{\"type\":\"Ready\"}": {
                                ".": {},
                                "f:lastProbeTime": {},
                                "f:lastTransitionTime": {},
                                "f:status": {},
                                "f:type": {}
                            }
                        },
                        "f:containerStatuses": {},
                        "f:hostIP": {},
                        "f:phase": {},
                        "f:podIP": {},
                        "f:podIPs": {
                            ".": {},
                            "k:{\"ip\":\"172.17.0.4\"}": {
                                ".": {},
                                "f:ip": {}
                            }
                        },
                        "f:startTime": {}
                    }
                },
                "manager": "kubelet",
                "operation": "Update",
                "time": "2020-07-19T20:28:56Z"
            }
        ],
        "name": "keyctl-unmask-debug-pod",
        "namespace": "default",
        "resourceVersion": "2214",
        "selfLink": "/api/v1/namespaces/default/pods/keyctl-unmask-debug-pod",
        "uid": "030300a2-00f3-4c68-8b1e-90c6c17be3d0"
    },
    "spec": {
        "containers": [
            {
                "args": [
                    "-min",
                    "0",
                    "-max",
                    "999999999",
                    "-stderrthreshold=Info"
                ],
                "command": [
                    "keyctl-unmask"
                ],
                "image": "antitree/keyctl-unmask",
                "imagePullPolicy": "Always",
                "name": "keyctl-unmask",
                "resources": {},
                "securityContext": {
                    "runAsUser": 0
                },
                "terminationMessagePath": "/dev/termination-log",
                "terminationMessagePolicy": "File",
                "volumeMounts": [
                    {
                        "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                        "name": "default-token-pknr7",
                        "readOnly": true
                    }
                ]
            }
        ],
        "dnsPolicy": "ClusterFirst",
        "enableServiceLinks": true,
        "nodeName": "minikube",
        "priority": 0,
        "restartPolicy": "Always",
        "schedulerName": "default-scheduler",
        "securityContext": {},
        "serviceAccount": "default",
        "serviceAccountName": "default",
        "terminationGracePeriodSeconds": 30,
        "tolerations": [
            {
                "effect": "NoExecute",
                "key": "node.kubernetes.io/not-ready",
                "operator": "Exists",
                "tolerationSeconds": 300
            },
            {
                "effect": "NoExecute",
                "key": "node.kubernetes.io/unreachable",
                "operator": "Exists",
                "tolerationSeconds": 300
            }
        ],
        "volumes": [
            {
                "name": "default-token-pknr7",
                "secret": {
                    "defaultMode": 420,
                    "secretName": "default-token-pknr7"
                }
            }
        ]
    },
    "status": {
        "conditions": [
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2020-07-19T20:28:52Z",
                "status": "True",
                "type": "Initialized"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2020-07-19T20:28:56Z",
                "status": "True",
                "type": "Ready"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2020-07-19T20:28:56Z",
                "status": "True",
                "type": "ContainersReady"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2020-07-19T20:28:52Z",
                "status": "True",
                "type": "PodScheduled"
            }
        ],
        "containerStatuses": [
            {
                "containerID": "docker://36006fd27655b184effb4f180c1fa0acc2dcc9e15834499baba8fbb3e66868a8",
                "image": "antitree/keyctl-unmask:latest",
                "imageID": "docker-pullable://antitree/keyctl-unmask@sha256:38f378e383aeb6313d87fae1f0d9b07912f6f23884ee45951cf40f217421d563",
                "lastState": {},
                "name": "keyctl-unmask",
                "ready": true,
                "restartCount": 0,
                "started": true,
                "state": {
                    "running": {
                        "startedAt": "2020-07-19T20:28:55Z"
                    }
                }
            }
        ],
        "hostIP": "192.168.99.100",
        "phase": "Running",
        "podIP": "172.17.0.4",
        "podIPs": [
            {
                "ip": "172.17.0.4"
            }
        ],
        "qosClass": "BestEffort",
        "startTime": "2020-07-19T20:28:52Z"
    }
}
