# keyutil-unmask Pod example
apiVersion: v1
kind: Pod
metadata:
  name: keyctl-unmask-debug-pod
spec:
  containers:
    - name: keyctl-unmask-debug
      image: antitree/keyctl-unmask
      # TODO just make this a web server so it's easier to read or something
      command: ['bash','-c','sleep 1000000']
      volumeMounts:
        - name: volume
          mountPath: /keyctl-output
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: keyctl-output


